# Generated by Django 4.1.3 on 2022-11-19 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(verbose_name='Start Time:')),
                ('end_time', models.DateTimeField(verbose_name='End Time:')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time:')),
                ('end_time', models.DateTimeField(verbose_name='End Time:')),
                ('exam_description', models.CharField(max_length=200)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_calendar.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(verbose_name='Due:')),
                ('assignment_description', models.CharField(max_length=200)),
                ('assigment_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_calendar.lecture')),
            ],
        ),
    ]
